Employee-CRUD_MVC_Core/Employee-CRUD/Controllers/QuotesController.cs
using Employee_CRUD.Bll;
using Employee_CRUD.Bll.Interface;
using Employee_CRUD.Filter;
using Employee_CRUD.Models;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Employee_CRUD.Controllers
{
    //[TypeFilter(typeof(CustomAuthorizationFilterAttribute))]
    public class QuotesController : Controller
    {
        [Obsolete]
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IQuotesBll _quotesBll;
        private readonly ITagsBll _tagsBll;
        private readonly ICategoryBll _categoryBll;

        [Obsolete]
        public QuotesController(IHostingEnvironment hostingEnvironment, IQuotesBll quotesBll, ICategoryBll categoryBll, ITagsBll tagsBll)
        {
            _hostingEnvironment = hostingEnvironment;
            _quotesBll = quotesBll;
            _categoryBll = categoryBll;
            _tagsBll = tagsBll;
        }

        public IActionResult Index()
        {
            ViewBag.Category = _categoryBll.GetAllCategoriesDropDown();
            ViewBag.Tags = _tagsBll.GetAllTagsByUserID();
            ViewBag.QuotesPosition = new List<SelectListItem>
            {
                  new SelectListItem { Text = "Top Left", Value = "Top Left"},
                  new SelectListItem { Text = "Top Center", Value = "Top Center"},
                  new SelectListItem { Text = "Top Right", Value = "Top Right"},
                  new SelectListItem { Text = "Center", Value = "Center", Selected=true},
                  new SelectListItem { Text = "Bottom Left", Value = "Bottom Left"},
                  new SelectListItem { Text = "Bottom Center", Value = "Bottom Center"},
                  new SelectListItem { Text = "Bottom Right", Value = "Bottom Right"}
            };
            return View();
        }
        [HttpPost]
        [Obsolete]
        public async Task<IActionResult> ManageQuotes(ManagePostModel sampleImageModel)
        {
            var path = Path.Combine(_hostingEnvironment.WebRootPath, @"Assets/Image/UserUploadedImages/");
            string fileName = DateTime.Now.Month.ToString() + DateTime.Now.Year.ToString() + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + DateTime.Now.Second.ToString() + DateTime.Now.Millisecond.ToString() + Path.GetExtension(sampleImageModel.ImageContent.FileName);
            var FileSaveLocation = path + fileName;
            if (sampleImageModel.ImageContent != null)
            {
                using (Stream fileStream = new FileStream(FileSaveLocation, FileMode.Create))
                {
                    await sampleImageModel.ImageContent.CopyToAsync(fileStream);
                }
            }
            else
            {
                //Select existing uploaded image
            }
            sampleImageModel.ImageName = DrawOverImageBll.DrawTextOverImage(sampleImageModel.QuoteText, FileSaveLocation, sampleImageModel.Position, sampleImageModel.FontColor, sampleImageModel.FontSize);
            _quotesBll.AddUpdatePublicPost(sampleImageModel);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public JsonResult DeletePostByPostID(int PostId)
        {
            var result = _quotesBll.DeletePostByPostID(PostId);
            return Json(new { result });
        }


        public ActionResult GetUserPost(DataTablesModel search)
        {
            var UserPostData = _quotesBll.GetAllUserPosts();

            var totalCount = UserPostData.Result.Count();
            if (search.iDisplayStart >= 0 && search.iDisplayLength > 0)
            {
                UserPostData.Result = UserPostData.Result.OrderByDescending(x => x.PostedDateTime).Skip(search.iDisplayStart).Take(search.iDisplayLength).ToList();
            }

            return Json(new DataTablesResponse<PostViewModel>(UserPostData.Result, totalCount, totalCount, search.sEcho));
        }

    }
}

Employee-CRUD_MVC_Core/Employee-CRUD/Views/Shared/_CommonLandingPageLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Quotes Application | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="@("/")assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="@("/")assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="@("/")assets/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    @RenderBody()
    <script src="@("/")assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="@("/")assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="@("/")assets/dist/js/adminlte.min.js"></script>
</body>
</html>

Employee-CRUD_MVC_Core/Employee-CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.Title</title>

    <link rel="shortcut icon" type="image/png" href="/favicon.png" />
    <link rel="shortcut icon" type="image/png" href="~/Assets/dist/img/neoparx.jpg" />

    <!-- Font Awesome Icons -->
    <link href="@("/")Assets/Plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="@("/")Assets/dist/css/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="~/Assets/Plugins/toastr/toastr.css" rel="stylesheet" />
    <link href="~/Assets/Plugins/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.3/flatpickr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" />
    <link href="~/Assets/Plugins/Select2/select2.min.css" rel="stylesheet" />

</head>
<body class="hold-transition layout-top-nav">
    <div class="d-flex justify-content-center">
        <div class="spinner-border" id="loadingDiv" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
            <div class="container">
                <a href="../../index3.html" class="navbar-brand">
                    <img src="/Assets/dist/img/neoparx.jpg" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                    <span class="brand-text font-weight-light">AdminLTE 3</span>
                </a>

                <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                    <!-- Left navbar links -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Quotes" asp-action="Index" class="nav-link">My Quotes</a>
                        </li>
                    </ul>

                    <!-- SEARCH FORM -->
                    <form class="form-inline ml-0 ml-md-3">
                        <div class="input-group input-group-sm">
                            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                            <div class="input-group-append">
                                <button class="btn btn-navbar" type="submit">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>

                <!-- Right navbar links -->
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    UserName
                    <!-- Notifications Dropdown Menu -->
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-toggle="dropdown" href="#">
                            <i class="far fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <a href="#" class="dropdown-item">
                                <i class="fa fa-user mr-2"></i> My Profile
                            </a>
                            <div class="dropdown-divider"></div>
                            <a href="#" class="dropdown-item">
                                <i class="fa fa-key mr-2"></i> Change Password
                            </a>
                            <div class="dropdown-divider"></div>
                            <a asp-controller="Account" asp-action="Logout" class="dropdown-item">
                                <i class="fa fa-lock mr-2"></i> Logout
                            </a>
                        </div>
                    </li>

                </ul>
            </div>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Side menu -->
            <a asp-controller="Home" asp-action="Index" class="brand-link">
                <img src="@("/")Assets/dist/img/neoparx.jpg" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Quotes Application</span>
            </a>
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                <div class="pt-3"></div>
                <div class="container">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="d-none d-sm-inline">
                Copyright © <b>Quotes Appplication</b> All rights reserved
            </div>
            <!-- Default to the left -->
        </footer>
    </div>

    <script src="@("/")Assets/Plugins/jquery/jquery.min.js"></script>
    <script src="@("/")Assets/Plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="@("/")Assets/dist/js/adminlte.min.js"></script>
    <script src="@("/")Assets/Plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="@("/")Assets/Plugins/jquery-validation/jquery.validate.js"></script>
    <script src="@("/")Assets/Plugins/jquery-validation/jquery.validate.unobtrusive.js"></script>
    <script src="@("/")Assets/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="@("/")Assets/Plugins/sweetalert2/sweetalert2.min.js"></script>
    <script src="@("/")Assets/Plugins/toastr/toastr.min.js"></script>
    @*<script src="@("/")Assets/Plugins/datatables/jquery.dataTables.min.js"></script>*@
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="@("/")Assets/Plugins/Select2/select2.min.js"></script>
    <script src="~/js/common.js"></script>

    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        var current = location.pathname;
        $('.list-group li a').removeClass('active');
        $('.list-group li a').each(function () {
            if ($(this).data("name") == current) {
                $(this).addClass('active');
            }
        });

        $(".tag-tokenizer").select2({
            tags: true,
            tokenSeparators: [',',' ']
        })
        var $loading = $('#loadingDiv').hide();
        $(document)
            .ajaxStart(function () {
                $loading.show();
            })
            .ajaxStop(function () {
                $loading.hide();
            });
    </script>
</body>
</html>